version: "3"
services:
  student:
    build:
      context: .
      target: development
    volumes:
      - .:/student:ro
    ports:
      - "9090:9090"
    environment:
      - PORTS=9090
      - PHASE_TYPE=DEV